# This is a basic workflow to help you get started with Actions

# ------------------------------------ #
#       Made By An V.1.0.0           #
# ------------------------------------ #
name: Test01
# ------------------------------------ #
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# ------------------------------------ #
jobs:
  metso:
    runs-on: ubuntu-20.04
    continue-on-error: True
    strategy:
      matrix:
        testi: [1.1, 27, 278, 2v, 9e, 93h, os, yys,]
        flaga: [Aqw, his, ]
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runneyr_go
      run: |
        sudo apt update -y && sleep 5
        
  roart-cont-1:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [1]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/config.json && timeout 350m php bot.php
      
  roart-cont-2:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [2]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai2.json -O config.json && timeout 350m php bot.php
            
  roart-cont-3:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [3]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai3.json -O config.json && timeout 350m php bot.php
      
  roart-cont-4:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [4]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai4.json -O config.json && timeout 350m php bot.php
            
  roart-cont-5:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [5]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai5.json -O config.json && timeout 350m php bot.php
  
  roart-cont-6:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [6]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai6.json -O config.json && timeout 350m php bot.php
  
  roart-cont-7:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [7]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai7.json -O config.json && timeout 350m php bot.php
            
  roart-cont-8:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [8]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai8.json -O config.json && timeout 350m php bot.php

  roart-cont-9:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [9]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai9.json -O config.json && timeout 350m php bot.php
              
  roart-cont-10:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [10]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/mai10.json -O config.json && timeout 350m php bot.php            
  
  roart-cont-11:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [11]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m11.json -O config.json && timeout 350m php bot.php
      
  roart-cont-12:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [12]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m12.json -O config.json && timeout 350m php bot.php
      
  roart-cont-13:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [13]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m13.json -O config.json && timeout 350m php bot.php
      
  roart-cont-14:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [14]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m14.json -O config.json && timeout 350m php bot.php
            
  roart-cont-15:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [15]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m15.json -O config.json && timeout 350m php bot.php
  
  roart-cont-16:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [16]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m16.json -O config.json && timeout 350m php bot.php
  
  roart-cont-17:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [17]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m17.json -O config.json && timeout 350m php bot.php
            
  roart-cont-18:
    needs: [metso]
    runs-on: ubuntu-latest
    continue-on-error: True
    strategy:
      matrix:
        cont-version: [18]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: EBroo iam .
      run: sudo apt-get update && sudo apt install php -y && mkdir mko && cd mko && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/frth.zip && unzip frth.zip && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/keys && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/conf/m18.json -O config.json && timeout 350m php bot.php

  
